# Change these first
owner: undp # Your GitHub organization or username, where this repository lives
repo: carbon-registry-status # The name of this repository

sites:
  - name: Carbon Registry
    url: https://www.test.carbreg.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  favicon: https://github.com/undp/carbon-registry-status/raw/master/assets/favicon.png
  baseUrl: /carbon-registry-status
#   cname: status.carbreg.org
  logoUrl: https://github.com/undp/carbon-registry-status/raw/master/assets/logo.svg
  name: Carbon Registry
  introTitle: "**Carbon Registry Status**"
  introMessage: "Carbon credit initiative for ExO and HQ/GEF"
  css: ".logo div{ display: none; }"
  navbar:
    - title: Status
      href: /
    - title: Carbon Registry
      href: https://www.test.carbreg.org/
      # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


workflowSchedule:
  graphs: "0 0 * * *"
  uptime: "0 */6 * * *"
